/*
 * LCD_Private.h
 *
 *  Created on: Apr 29, 2023
 *      Author: dell
 */

#ifndef INCLUDE_HAL_LCD_LCD_PRIVATE_H_
#define INCLUDE_HAL_LCD_LCD_PRIVATE_H_

#define DISPLAY_CLEAR  1
#define RETURN_HOME    2
#define ENTRY_MODE_SET CONC_BIT(0,0,0,0,0,1,I_D,SHIFT)
#define DISPLAY_ON_OFF CONC_BIT(0,0,0,0,1,DISPLAY_ON,CURSOR_DISPLAY,CURSOR_BLINK)
#define DISPLAY_SHIFT  CONC_BIT(0,0,0,1,SC,RL,0,0)
#define FUNCTION_SET   CONC_BIT(0,0,1,DATA_LENGTH,NO_OF_LINES,CHAR_FONT,0,0)




#define ROW1_ADDRESS 127
#define ROW2_ADDRESS 191

#endif /* INCLUDE_HAL_LCD_LCD_PRIVATE_H_ */
