/*
 * DIO_cfg.h
 *
 *  Created on: Apr 28, 2023
 *      Author: dell
 */

#ifndef INCLUDE_MCAL_DIO_DIO_CFG_H_
#define INCLUDE_MCAL_DIO_DIO_CFG_H_

#define DIO_CFG_INPUT 0
#define DIO_CFG_OUTPUT 1

#define DIO_CFG_HIGH 1
#define DIO_CFG_LOW  0

#define DIO_CFG_FLOATING 0
#define DIO_CFG_PULLUP   1

//for PORT A
#define PORTA_P0_DIRECTION DIO_CFG_OUTPUT
#define PORTA_P1_DIRECTION DIO_CFG_OUTPUT
#define PORTA_P2_DIRECTION DIO_CFG_OUTPUT
#define PORTA_P3_DIRECTION DIO_CFG_OUTPUT
#define PORTA_P4_DIRECTION DIO_CFG_OUTPUT
#define PORTA_P5_DIRECTION DIO_CFG_INPUT
#define PORTA_P6_DIRECTION DIO_CFG_INPUT
#define PORTA_P7_DIRECTION DIO_CFG_INPUT

//for PORT B
#define PORTB_P0_DIRECTION DIO_CFG_INPUT
#define PORTB_P1_DIRECTION DIO_CFG_INPUT
#define PORTB_P2_DIRECTION DIO_CFG_INPUT
#define PORTB_P3_DIRECTION DIO_CFG_INPUT
#define PORTB_P4_DIRECTION DIO_CFG_INPUT
#define PORTB_P5_DIRECTION DIO_CFG_INPUT
#define PORTB_P6_DIRECTION DIO_CFG_INPUT
#define PORTB_P7_DIRECTION DIO_CFG_INPUT

//for PORT C
#define PORTC_P0_DIRECTION DIO_CFG_OUTPUT
#define PORTC_P1_DIRECTION DIO_CFG_OUTPUT
#define PORTC_P2_DIRECTION DIO_CFG_OUTPUT
#define PORTC_P3_DIRECTION DIO_CFG_OUTPUT
#define PORTC_P4_DIRECTION DIO_CFG_OUTPUT
#define PORTC_P5_DIRECTION DIO_CFG_OUTPUT
#define PORTC_P6_DIRECTION DIO_CFG_OUTPUT
#define PORTC_P7_DIRECTION DIO_CFG_OUTPUT

//for PORT D
#define PORTD_P0_DIRECTION DIO_CFG_INPUT
#define PORTD_P1_DIRECTION DIO_CFG_INPUT
#define PORTD_P2_DIRECTION DIO_CFG_INPUT
#define PORTD_P3_DIRECTION DIO_CFG_OUTPUT
#define PORTD_P4_DIRECTION DIO_CFG_OUTPUT
#define PORTD_P5_DIRECTION DIO_CFG_OUTPUT
#define PORTD_P6_DIRECTION DIO_CFG_INPUT
#define PORTD_P7_DIRECTION DIO_CFG_INPUT

/************************************************************/

//for PORT A
#define PORTA_P0_VALUE DIO_CFG_LOW
#define PORTA_P1_VALUE DIO_CFG_HIGH
#define PORTA_P2_VALUE DIO_CFG_LOW
#define PORTA_P3_VALUE DIO_CFG_HIGH
#define PORTA_P4_VALUE DIO_CFG_LOW
#define PORTA_P5_VALUE DIO_CFG_FLOATING
#define PORTA_P6_VALUE DIO_CFG_FLOATING
#define PORTA_P7_VALUE DIO_CFG_FLOATING

//for PORT B
#define PORTB_P0_VALUE DIO_CFG_FLOATING
#define PORTB_P1_VALUE DIO_CFG_FLOATING
#define PORTB_P2_VALUE DIO_CFG_FLOATING
#define PORTB_P3_VALUE DIO_CFG_FLOATING
#define PORTB_P4_VALUE DIO_CFG_FLOATING
#define PORTB_P5_VALUE DIO_CFG_FLOATING
#define PORTB_P6_VALUE DIO_CFG_FLOATING
#define PORTB_P7_VALUE DIO_CFG_FLOATING

//for PORT C
#define PORTC_P0_VALUE DIO_CFG_LOW
#define PORTC_P1_VALUE DIO_CFG_LOW
#define PORTC_P2_VALUE DIO_CFG_LOW
#define PORTC_P3_VALUE DIO_CFG_LOW
#define PORTC_P4_VALUE DIO_CFG_LOW
#define PORTC_P5_VALUE DIO_CFG_LOW
#define PORTC_P6_VALUE DIO_CFG_LOW
#define PORTC_P7_VALUE DIO_CFG_LOW

//for PORT D
#define PORTD_P0_VALUE DIO_CFG_FLOATING
#define PORTD_P1_VALUE DIO_CFG_FLOATING
#define PORTD_P2_VALUE DIO_CFG_FLOATING
#define PORTD_P3_VALUE DIO_CFG_LOW
#define PORTD_P4_VALUE DIO_CFG_LOW
#define PORTD_P5_VALUE DIO_CFG_LOW
#define PORTD_P6_VALUE DIO_CFG_FLOATING
#define PORTD_P7_VALUE DIO_CFG_FLOATING



#endif /* INCLUDE_MCAL_DIO_DIO_CFG_H_ */
